version: 0.2

phases:
  install:
    commands:
      - echo "Installing GitVersion..."
      - dotnet tool install --global GitVersion.Tool --version 6.0.2
      # В AWS CodeBuild standard:7.0 .NET 6.0 уже установлен, поэтому мы не указываем runtime-versions: dotnet
      - export PATH="$PATH:/root/.dotnet/tools"
      
  pre_build:
    commands:
      - echo "Calculating Semantic Version using GitVersion v6..."
      - IMAGE_TAG=$(dotnet-gitversion /output json /showvariable SemVer)
      - echo "Calculated version is $IMAGE_TAG"
      - export VERSION=$IMAGE_TAG

  build:
    commands:
      - echo "Building with version $VERSION..."
      # docker build -t my-app:$VERSION .
